### PR TITLE
[sc-143139] push-notifications-2 /send payload update

### PR DESCRIPTION
**Pull request by ahrabovenskyi**
Updating payload to send just `ssoId` instead if `users` array with single element.

So changing payload from:

```
{
    "users": [
        "651424a9e7aa4c000e26bf32"
    ],
    "ios": {
        "badge": 4,
        "alert": "Andrii H. says: \"hey!\"",
        "sound": "default",
        "payload": {
            "type": "message",
            "message-id": "ly6ucto452c",
            "booking-id": "6634b98fb85da6cdb162198d"
        }
    }
}
```
to
```
{
    "ssoId": "651424a9e7aa4c000e26bf32",
    "ios": {
        "badge": 4,
        "alert": "Andrii H. says: \"hey!\"",
        "sound": "default",
        "payload": {
            "type": "message",
            "message-id": "ly6ucto452c",
            "booking-id": "6634b98fb85da6cdb162198d"
        }
    }
}
```

This change is possible since we always send push notification to a single user.
Note: this service/repo will be removed next weeks

[sc-143139]

### CODE REVIEW

**Review by lukaszkorecki-ps — APPROVED** [review]
I get it, but what's the background behind this change?

**Comment by ahrabovenskyi** [comment]
@lukaszkorecki-ps here is the background https://app.shortcut.com/peerspace/story/143139/sending-transactional-message-to-multiple-users-at-once#activity-144087
we can get on call if you have any questions about this since I'm afraid that this explanation may be confusing

**Comment by lukaszkorecki-ps** [comment]
> @lukaszkorecki-ps here is the background https://app.shortcut.com/peerspace/story/143139/sending-transactional-message-to-multiple-users-at-once#activity-144087 we can get on call if you have any questions about this since I'm afraid that this explanation may be confusing

Thanks! It makes sense - just one thing - which repo is the new push service and which one is the old one?

**Comment by ahrabovenskyi** [comment]
> > @lukaszkorecki-ps here is the background https://app.shortcut.com/peerspace/story/143139/sending-transactional-message-to-multiple-users-at-once#activity-144087 we can get on call if you have any questions about this since I'm afraid that this explanation may be confusing
> 
> Thanks! It makes sense - just one thing - which repo is the new push service and which one is the old one?

this one is old.
The new one: https://github.com/peerspace/push-notifications

**Pull request merged**
